import { Fragment } from 'react'
import '../styles/vanilla.scss'
// import '../styles/globals.css'
import { AppProps } from 'next/app'
import Head from 'next/head'
import NavBar from '../components/NavBar'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Fragment>
      <Head>
        <title>Canonical Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Component {...pageProps} />
    </Fragment>
  )
}

export default MyApp
